リリース作業
yanbaru-expert/team_project_45 pull request #58
Opened 2021-11-23 14:08 UTC by akko-k

close #48

## 実装内容

- ブランチ名は `release/1.0` とすること
- Herokuにプッシュした際に自動でマイグレーションを行う設定を追加
```
echo "release: bin/rails db:migrate" > Procfile
```

- Heroku アプリを作成
  - ステージング環境は作成しなくてもOK
  - 自動デプロイ設定は，権限の都合上対応が難しいため，設定しない

- コミットした上で Heroku にデプロイし，初期データを投入
  - エラーが出た場合は対応

```
git push heroku HEAD:main
heroku run rails db:seed
```

- 動作確認を行い，異常を発見した場合は対応

## チェックリスト

【補足】プルリクを出した後，クリックでチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

## 備考（必要があれば）
- HerokuのアプリのURL
https://yanbaru45.herokuapp.com/

2021-11-28 10:13 UTC, T-Tsujii requested changes

2021-11-28 10:13 UTC, T-Tsujii commented on app/views/devise/shared/_links.html.erb
> +  <!--<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
HTMLとしてのコメントアウトは「デベロッパーツール」や「ページのソースを表示」から見えてしまいますので，
erbのコメントアウトを使用した方がよいですね。
（ここはセキュリティ的な問題は発生しないのでどちらでも問題はありませんが）

```rb
<%# コメントアウト %>
```

2021-11-28 10:28 UTC, T-Tsujii requested changes

2021-11-28 10:28 UTC, T-Tsujii commented on Procfile
> +git add Procfilerelease: bin/rails db:migrate
gitのコマンドが入ってしまっていますね。

```suggestion
release: bin/rails db:migrate
```

2021-11-29 10:13 UTC, T-Tsujii approved these changes
LGTMです！

2021-11-29 14:04 UTC, MotokiTakashima commented
LGTMです！

2021-11-30 11:49 UTC, merged